baseURL = "http://example.org/"
languageCode = "en-us"
title = "Better Call Paper"

[[params.mainMenu]]
    link = "/about"
    text = "Better Call Paper"

[[params.mainMenu]]
    link = "/posts"
    text = "writing"
